#!/bin/bash
# One-time (idempotent) Mac setup for macsim. Normally launched by `macsim bootstrap`
# from the client machine; safe to re-run by hand:  bash ~/.macsim/setup.sh
# Must stay compatible with macOS /bin/bash 3.2.
set -u
MACSIM_HOME="$HOME/.macsim"
AD_VERSION="" PC_HOST="" PC_USER="" PORT="" BIND=""
while [ $# -gt 0 ]; do case "$1" in
  --agent-device-version) AD_VERSION="$2"; shift 2 ;;
  --pc-host) PC_HOST="$2"; shift 2 ;;
  --pc-user) PC_USER="$2"; shift 2 ;;
  --port) PORT="$2"; shift 2 ;;
  --proxy-bind) BIND="$2"; shift 2 ;;
  *) echo "unknown arg $1" >&2; exit 1 ;; esac; done

HAD_CONFIG=0
# shellcheck disable=SC1091
[ -f "$MACSIM_HOME/config" ] && { . "$MACSIM_HOME/config"; HAD_CONFIG=1; }
AD_VERSION="${AD_VERSION:-${AGENT_DEVICE_VERSION:-latest}}"
SERVE_SIM_VERSION="${SERVE_SIM_VERSION:-0.1.47}"
PORT="${PORT:-${PROXY_PORT:-4310}}"
# Explicit flag > existing config > legacy configs (bound to Tailscale) > loopback (SSH tunnel).
if [ -z "$BIND" ]; then
  if [ -n "${PROXY_BIND:-}" ]; then BIND="$PROXY_BIND"
  elif [ "$HAD_CONFIG" = 1 ]; then BIND=tailscale
  else BIND=127.0.0.1; fi
fi
# Keep using ~/builds on installs that already have projects there.
if [ -z "${BUILDS:-}" ]; then
  if ls "$HOME"/builds/*/.last-used >/dev/null 2>&1; then BUILDS="$HOME/builds"; else BUILDS="$MACSIM_HOME/builds"; fi
fi

step() { printf '\n\033[1m== %s\033[0m\n' "$*"; }
ask()  { printf '%s [y/N] ' "$1"; read -r a </dev/tty; [ "$a" = y ] || [ "$a" = Y ]; }
mkdir -p "$MACSIM_HOME/bin" "$MACSIM_HOME/logs" "$BUILDS"

step "Xcode"
if ! xcode-select -p 2>/dev/null | grep -q Xcode; then
  if [ -d /Applications/Xcode.app ]; then
    sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
  else
    echo "Xcode is not installed. Install it from the App Store (or with 'xcodes'), then re-run: bash ~/.macsim/setup.sh"; exit 1
  fi
fi
xcodebuild -version >/dev/null 2>&1 || sudo xcodebuild -license accept
xcodebuild -checkFirstLaunchStatus >/dev/null 2>&1 || xcodebuild -runFirstLaunch
xcodebuild -version | head -1
if ! xcrun simctl list runtimes | grep -q '^iOS'; then
  echo "No iOS simulator runtime installed (~8 GB). Free disk: $(df -h "$HOME" | awk 'NR==2{print $4}')"
  ask "Download it now?" && xcodebuild -downloadPlatform iOS
fi

step "Node"
NODE_DIR=""
# Must be real Node >= 20 (a `node` shim from another runtime won't do).
real_node() { "$1" -e 'process.exit(process.release.name==="node" && +process.versions.node.split(".")[0]>=20 ? 0 : 1)' 2>/dev/null; }
for c in /opt/homebrew/bin/node /usr/local/bin/node "$HOME"/.volta/bin/node "$HOME"/.nvm/versions/node/*/bin/node \
         "$HOME"/.local/share/fnm/aliases/default/bin/node "$(command -v node 2>/dev/null)"; do
  [ -n "$c" ] && [ -x "$c" ] && real_node "$c" && { NODE_DIR="$(dirname "$c")"; break; }
done
if [ -z "$NODE_DIR" ]; then
  BREW="$(command -v brew || ls /opt/homebrew/bin/brew /usr/local/bin/brew 2>/dev/null | head -1)"
  if [ -n "$BREW" ] && ask "Node >= 20 not found. Install it with Homebrew?"; then
    "$BREW" install node && NODE_DIR="$("$BREW" --prefix)/bin"
  else
    echo "Node >= 20 not found. Install it (https://nodejs.org or Homebrew) and re-run."; exit 1
  fi
fi
echo "node: $NODE_DIR/node ($("$NODE_DIR/node" -v))"

cat >"$MACSIM_HOME/env.sh" <<EOF
# generated by macsim setup.sh
export PATH="$MACSIM_HOME/tools/node_modules/.bin:$MACSIM_HOME/bin:$NODE_DIR:/opt/homebrew/bin:/usr/local/bin:\$HOME/.local/bin:\$PATH"
export LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8
EOF
# shellcheck disable=SC1091
. "$MACSIM_HOME/env.sh"

step "agent-device@$AD_VERSION + serve-sim@$SERVE_SIM_VERSION (private install in ~/.macsim/tools)"
mkdir -p "$MACSIM_HOME/tools"
[ -f "$MACSIM_HOME/tools/package.json" ] || echo '{"private":true}' >"$MACSIM_HOME/tools/package.json"
(cd "$MACSIM_HOME/tools" && npm install --no-fund --no-audit "agent-device@$AD_VERSION" "serve-sim@$SERVE_SIM_VERSION") \
  || { echo "agent-device/serve-sim install failed"; exit 1; }
agent-device --version

step "Optional tools"
if ! command -v pod >/dev/null; then
  if command -v brew >/dev/null; then ask "Install CocoaPods (needed for React Native / Expo builds)?" && brew install cocoapods
  else echo "CocoaPods missing and no Homebrew. React Native / Expo builds need it (https://cocoapods.org)"; fi
fi
if command -v brew >/dev/null && ! command -v xcodegen >/dev/null; then
  ask "Install XcodeGen (only needed for projects with a project.yml)?" && brew install xcodegen
fi
if command -v brew >/dev/null && ! "$(brew --prefix)/bin/rsync" --version >/dev/null 2>&1; then
  ask "Install a modern rsync (faster and more compatible than macOS openrsync)?" && brew install rsync
fi

step "Config (~/.macsim/config)"
cat >"$MACSIM_HOME/config" <<EOF
# macsim config (Mac side). Re-running setup.sh keeps these values.
PROXY_PORT=$PORT
# where the agent-device proxy listens: 127.0.0.1 (via SSH tunnel) | tailscale | <ip>
PROXY_BIND=$BIND
# per-project working copies, caches and DerivedData
BUILDS="$BUILDS"
AGENT_DEVICE_VERSION=$AD_VERSION
SERVE_SIM_VERSION=$SERVE_SIM_VERSION
# 1 = show the simulator window (Simulator.app / DeviceHub) when booting
SIM_GUI=${SIM_GUI:-1}
# simulator used when none is given (empty = booted one, else newest plain iPhone)
DEFAULT_DEVICE="${DEFAULT_DEVICE:-}"
EOF
grep -v '^#' "$MACSIM_HOME/config"
if [ -s "$MACSIM_HOME/token" ]; then chmod 600 "$MACSIM_HOME/token"
else echo "WARNING: $MACSIM_HOME/token missing (macsim bootstrap copies it)"; fi

step "agent-device proxy LaunchAgent"
PLIST="$HOME/Library/LaunchAgents/com.macsim.proxy.plist"
mkdir -p "$HOME/Library/LaunchAgents"
cat >"$PLIST" <<EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key><string>com.macsim.proxy</string>
  <key>ProgramArguments</key><array><string>/bin/bash</string><string>$MACSIM_HOME/bin/proxy-run.sh</string></array>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>ThrottleInterval</key><integer>15</integer>
  <key>ProcessType</key><string>Interactive</string>
  <key>StandardOutPath</key><string>$MACSIM_HOME/logs/proxy.log</string>
  <key>StandardErrorPath</key><string>$MACSIM_HOME/logs/proxy.log</string>
</dict></plist>
EOF
dom="gui/$(id -u)"
launchctl bootout "$dom/com.macsim.proxy" >/dev/null 2>&1
launchctl bootstrap "$dom" "$PLIST" && echo "proxy LaunchAgent loaded (log: ~/.macsim/logs/proxy.log)"
[ "$BIND" = 127.0.0.1 ] || echo "If macOS asks whether 'node' may accept incoming connections: click Allow."

step "Shell PATH"
for rc in "$HOME/.zshrc" "$HOME/.bash_profile"; do
  [ -f "$rc" ] || [ "$rc" = "$HOME/.zshrc" ] || continue
  # shellcheck disable=SC2016  # $HOME/$PATH must stay literal in the rc file
  grep -q '.macsim/bin' "$rc" 2>/dev/null || { echo 'export PATH="$HOME/.macsim/bin:$PATH"  # macsim' >>"$rc"; echo "added ~/.macsim/bin to PATH in $rc"; }
done

if [ -n "$PC_HOST" ]; then
  step "Mac -> client access (optional 'pc' command)"
  mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
  [ -f "$HOME/.ssh/id_ed25519" ] || ssh-keygen -t ed25519 -N "" -f "$HOME/.ssh/id_ed25519" -C "$(whoami)@mac-macsim" >/dev/null
  if ! grep -q '^Host pc$' "$HOME/.ssh/config" 2>/dev/null; then
    mkdir -p "$HOME/.ssh/cm"
    cat >>"$HOME/.ssh/config" <<EOF

# added by macsim
Host pc
    HostName $PC_HOST
    User $PC_USER
    ControlMaster auto
    ControlPath ~/.ssh/cm/%r@%h:%p
    ControlPersist 10m
    ServerAliveInterval 15
EOF
    echo "added 'Host pc' ($PC_USER@$PC_HOST) to ~/.ssh/config"
  fi
fi

step "Done"
bash "$MACSIM_HOME/bin/macsim-remote" doctor
cat <<'EOF'

On the Mac (open a new terminal first so PATH is updated):
  macserver on       stay awake with the lid closed (keep it on the charger)
  macserver off      normal sleep again
  macserver status
  pc                 tmux session on the client machine (if enabled)
EOF
